name: UltimateCars
version: 0.0.3_01
author: CrashGamesCrMc
main: io.github.crashgamescrmc.UltimateCars.UltimateCars
description: A minecraft plugin that turns off rail minecarts into cars.
depend:
- Vault
- ProtocolLib
commands:
  cars:
    description: Shows the version